# ----------------------- #
#      Main Configs       #
# ----------------------- #

baseurl: "http://www.danpiessens.com"
title: "Another Level of Indirection"
canonifyurls: true
footnotereturnlinkcontents: "↩"
paginate: 10
theme: "startbootstrap-clean-blog"
metaDataFormat: "yaml"
languageCode: "en-us"
copyright: "2015 Dan Piessens, All rights reserved."

author:
  name: "Dan Piessens"

# permalinks: 
#   post: /:year/:month/:day/:title/
  
params:
  DateForm: "January 2, 2006"
  Subtitle: "A journey through the endless maze of Agile, DevOps, technology and life."
  Author: "Dan Piessens"
  GitHubUser: "dpiessens"
  Ganalytics: "UA-46643958-2"
  disqusShortname: dpiessens
  SidebarRecentLimit: 5
  social:
    - title: twitter
      url: "https://twitter.com/dpiessens"
    - title: github
      url: "https://github.com/dpiessens"    
 
menu:
  main:
  - name: home
    url: /
    weight: -200
  - name: Archives
    url: /post/
    weight: -180
